// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8DZN9jKAcNmpbUD15rj5-p2OuDhdk7hM',
    appId: '1:606062160176:web:104264d6d55f3db17d80f5',
    messagingSenderId: '606062160176',
    projectId: 'minimal-app-2944f',
    authDomain: 'minimal-app-2944f.firebaseapp.com',
    storageBucket: 'minimal-app-2944f.appspot.com',
    measurementId: 'G-E99VE8E61G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPENjhdBujvTG4l6HDrqAXu-akASraPkw',
    appId: '1:606062160176:android:44e80de5ec74d1c07d80f5',
    messagingSenderId: '606062160176',
    projectId: 'minimal-app-2944f',
    storageBucket: 'minimal-app-2944f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4xm09BAKtkahAdc0M2tP7WO6QtZvl5Qc',
    appId: '1:606062160176:ios:d6cf9fe4e47095c07d80f5',
    messagingSenderId: '606062160176',
    projectId: 'minimal-app-2944f',
    storageBucket: 'minimal-app-2944f.appspot.com',
    iosBundleId: 'com.example.minimalSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4xm09BAKtkahAdc0M2tP7WO6QtZvl5Qc',
    appId: '1:606062160176:ios:5b0664217dadc9387d80f5',
    messagingSenderId: '606062160176',
    projectId: 'minimal-app-2944f',
    storageBucket: 'minimal-app-2944f.appspot.com',
    iosBundleId: 'com.example.minimalSocialApp.RunnerTests',
  );
}
